# Generated by Django 5.1.7 on 2025-04-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_station_username'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.fournisseur'),
        ),
    ]
