# Generated by Django 5.2 on 2025-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_station_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='connector_types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='nom',
            field=models.CharField(default='Station de recharge', max_length=100),
        ),
        migrations.AddField(
            model_name='station',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='power',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='adresse',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
