# Generated by Django 5.2 on 2025-04-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_station_connector_types_station_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='username',
        ),
    ]
