# Generated by Django 5.2 on 2025-04-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_remove_station_username'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.fournisseur'),
        ),
    ]
