# Generated by Django 5.2 on 2025-04-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_station_username'),
        ('users', '0002_users_is_active_users_is_admin_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avi',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.proprietaireve'),
        ),
        migrations.AlterField(
            model_name='station',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.fournisseur', verbose_name='Fournisseur'),
        ),
    ]
